Repository wazuh/wazuh-packages, pull requests merged in 2021-01, with the labels that each got.

#590 Fixed HPUX checksum generation
  hp-ux/generate_wazuh_packages.sh
Labels: bug, build-tools, hp-ux

#592 Backup api.yaml configuration file to restore it when upgrading
  debs/SPECS/4.1.0/wazuh-manager/debian/postinst
  debs/SPECS/4.1.0/wazuh-manager/debian/preinst
  debs/SPECS/4.2.0/wazuh-manager/debian/postinst
  debs/SPECS/4.2.0/wazuh-manager/debian/preinst
  debs/SPECS/5.0.0/wazuh-manager/debian/postinst
  debs/SPECS/5.0.0/wazuh-manager/debian/preinst
Labels: cicd

#600 Back port changes from #592
  debs/SPECS/4.0.4/wazuh-manager/debian/postinst
  debs/SPECS/4.0.4/wazuh-manager/debian/preinst
Labels: bug, deb

#605 Changed OVA name
  ova/wazuh_ovf_template
Labels: ova

#588 Fix solaris11: state and pid files for wazuh daemons renaming
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
Labels: SPECS, solaris

#603 Removing the ossec-init.conf usage from all the packages
  aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
  aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
  debs/SPECS/4.2.0/wazuh-agent/debian/postinst
  debs/SPECS/4.2.0/wazuh-agent/debian/rules
  debs/SPECS/4.2.0/wazuh-manager/debian/postinst
  debs/SPECS/4.2.0/wazuh-manager/debian/rules
  debs/SPECS/5.0.0/wazuh-agent/debian/postinst
  debs/SPECS/5.0.0/wazuh-agent/debian/rules
  debs/SPECS/5.0.0/wazuh-manager/debian/postinst
  debs/SPECS/5.0.0/wazuh-manager/debian/rules
  hp-ux/generate_wazuh_packages.sh
  macos/package_files/4.2.0/postinstall.sh
  macos/package_files/4.2.0/preinstall.sh
  macos/package_files/5.0.0/postinstall.sh
  macos/package_files/5.0.0/preinstall.sh
  macos/specs/4.x/wazuh-agent-4.2.0.pkgproj
  macos/specs/4.x/wazuh-agent-5.0.0.pkgproj
  macos/uninstall.sh
  rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris10/generate_wazuh_packages.sh
  solaris/solaris10/preinstall.sh
  solaris/solaris10/preremove.sh
  solaris/solaris10/uninstall.sh
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
  solaris/solaris11/generate_wazuh_packages.sh
  solaris/solaris11/solaris_fix.py
  solaris/solaris11/uninstall.sh
Labels: enhancement

#602 Replacing the tag WAZUH_HOME with WAZUH_HOME_TMP
  aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
  aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
  debs/SPECS/4.2.0/wazuh-agent/debian/postinst
  debs/SPECS/4.2.0/wazuh-agent/debian/rules
  debs/SPECS/4.2.0/wazuh-manager/debian/postinst
  debs/SPECS/4.2.0/wazuh-manager/debian/rules
  debs/SPECS/5.0.0/wazuh-agent/debian/postinst
  debs/SPECS/5.0.0/wazuh-agent/debian/rules
  debs/SPECS/5.0.0/wazuh-manager/debian/postinst
  debs/SPECS/5.0.0/wazuh-manager/debian/rules
  hp-ux/generate_wazuh_packages.sh
  macos/package_files/4.2.0/postinstall.sh
  macos/package_files/4.2.0/preinstall.sh
  macos/package_files/5.0.0/postinstall.sh
  macos/package_files/5.0.0/preinstall.sh
  macos/specs/4.x/wazuh-agent-4.2.0.pkgproj
  macos/specs/4.x/wazuh-agent-5.0.0.pkgproj
  macos/uninstall.sh
  rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris10/generate_wazuh_packages.sh
  solaris/solaris10/preinstall.sh
  solaris/solaris10/preremove.sh
  solaris/solaris10/uninstall.sh
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
  solaris/solaris11/generate_wazuh_packages.sh
  solaris/solaris11/solaris_fix.py
  solaris/solaris11/uninstall.sh
Labels: enhancement

#610 Fixing wazuh-control parameters in the calls to get the Wazuh version
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
Labels: testing

#596 Add wazuh-logcollector.state to solaris SPECS
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
Labels: SPECS, solaris

#623 Port the changes from Wazuh 4.2.x to 5.0
  debs/SPECS/5.0.0/wazuh-agent/debian/postinst
  debs/SPECS/5.0.0/wazuh-agent/debian/preinst
  debs/SPECS/5.0.0/wazuh-agent/debian/prerm
  debs/SPECS/5.0.0/wazuh-agent/debian/rules
  debs/SPECS/5.0.0/wazuh-manager/debian/postinst
  debs/SPECS/5.0.0/wazuh-manager/debian/preinst
  debs/SPECS/5.0.0/wazuh-manager/debian/prerm
  debs/SPECS/5.0.0/wazuh-manager/debian/rules
  macos/package_files/5.0.0/postinstall.sh
  macos/package_files/5.0.0/preinstall.sh
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
Labels: enhancement
