Repository wazuh/wazuh-packages, pull requests merged in 2021-02, with the labels that each got.

#624 2nd iteration over motd ASCII art
  ova/provision.sh
Labels: operations, ova

#609 Removal of the ossec-init.conf file from the Wazuh installations - Packages changes implementation
  aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
  aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
  debs/SPECS/4.2.0/wazuh-agent/debian/postinst
  debs/SPECS/4.2.0/wazuh-agent/debian/rules
  debs/SPECS/4.2.0/wazuh-manager/debian/postinst
  debs/SPECS/4.2.0/wazuh-manager/debian/rules
  debs/SPECS/5.0.0/wazuh-agent/debian/postinst
  debs/SPECS/5.0.0/wazuh-agent/debian/rules
  debs/SPECS/5.0.0/wazuh-manager/debian/postinst
  debs/SPECS/5.0.0/wazuh-manager/debian/rules
  hp-ux/generate_wazuh_packages.sh
  macos/package_files/4.2.0/postinstall.sh
  macos/package_files/4.2.0/preinstall.sh
  macos/package_files/5.0.0/postinstall.sh
  macos/package_files/5.0.0/preinstall.sh
  macos/specs/4.x/wazuh-agent-4.2.0.pkgproj
  macos/specs/4.x/wazuh-agent-5.0.0.pkgproj
  macos/uninstall.sh
  rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris10/generate_wazuh_packages.sh
  solaris/solaris10/preinstall.sh
  solaris/solaris10/preremove.sh
  solaris/solaris10/uninstall.sh
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
  solaris/solaris11/generate_wazuh_packages.sh
  solaris/solaris11/solaris_fix.py
  solaris/solaris11/uninstall.sh
Labels: enhancement

#630 Cmake build
  aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
  aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
  aix/generate_wazuh_packages.sh
  debs/Debian/amd64/Dockerfile
  debs/Debian/arm64/Dockerfile
  debs/Debian/armhf/Dockerfile
  debs/Debian/i386/Dockerfile
  debs/Debian/ppc64le/Dockerfile
  debs/SPECS/4.2.0/wazuh-agent/debian/rules
  debs/SPECS/4.2.0/wazuh-manager/debian/rules
  debs/build.sh
  rpms/CentOS/5/i386/Dockerfile
  rpms/CentOS/5/x86_64/Dockerfile
  rpms/CentOS/6/i386/Dockerfile
  rpms/CentOS/6/x86_64/Dockerfile
  rpms/CentOS/7/aarch64/Dockerfile
  rpms/CentOS/7/armv7hl/Dockerfile
  rpms/CentOS/7/ppc64le/Dockerfile
  rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris11/SPECS/template_agent_v4.2.0.json
  solaris/solaris11/SPECS/template_agent_v5.0.0.json
  windows/Dockerfile
  wpk/linux/x86_64/Dockerfile
Labels: priority/alpha

#647 Added TARGET selector in make deps
  aix/SPECS/4.2.0/wazuh-agent-4.2.0-aix.spec
  aix/SPECS/5.0.0/wazuh-agent-5.0.0-aix.spec
  debs/SPECS/4.2.0/wazuh-agent/debian/rules
  debs/SPECS/4.2.0/wazuh-manager/debian/rules
  debs/SPECS/5.0.0/wazuh-agent/debian/rules
  debs/SPECS/5.0.0/wazuh-manager/debian/rules
  hp-ux/generate_wazuh_packages.sh
  macos/package_files/4.2.0/build.sh
  macos/package_files/5.0.0/build.sh
  rpms/SPECS/4.2.0/wazuh-agent-4.2.0.spec
  rpms/SPECS/4.2.0/wazuh-manager-4.2.0.spec
  rpms/SPECS/5.0.0/wazuh-agent-5.0.0.spec
  rpms/SPECS/5.0.0/wazuh-manager-5.0.0.spec
  solaris/solaris10/generate_wazuh_packages.sh
  solaris/solaris11/generate_wazuh_packages.sh
  windows/entrypoint.sh
  wpk/run.sh
Labels: enhancement

#631 Configuration tags normalization to Wazuh standard - Packages changes implementation
  ova/Config_files/ossec.conf
Labels: enhancement
