Repository wazuh/wazuh-packages, pull requests merged in 2022-10, with the labels that each got.

#1877 Fix package conflicts between `wazuh-manager` and `azure-cli` on CentOS 8
  rpms/SPECS/wazuh-manager.spec
Labels: rpm

#1895 Fix 4.3.9 release changelog 4.4
  CHANGELOG.md
  rpms/SPECS/wazuh-agent.spec
Labels: hacktoberfest

#1898 Remove `Wazuh dashboard` and `Wazuh indexer` `init.d` service for `Red Hat 9` 4.4
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type: bug, rpm, hacktoberfest, hacktoberfest-accepted

#1899 Remove `Wazuh dashboard` and `Wazuh indexer` `init.d` service for `Red Hat 9` master
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/rpm/wazuh-indexer.spec
Labels: hacktoberfest

#1876 Remove deprecated apt-key from the installation assistant
  unattended_installer/builder.sh
  unattended_installer/common_functions/common.sh
  unattended_installer/install_functions/installCommon.sh
Labels: component: installation-assistant

#1904 Parameterize Wazuh dashboard script 4.4
  stack/dashboard/deb/build_package.sh
  stack/dashboard/deb/builder.sh
  stack/dashboard/deb/debian/rules
  stack/dashboard/rpm/build_package.sh
  stack/dashboard/rpm/builder.sh
  stack/dashboard/rpm/wazuh-dashboard.spec
Labels: type: feature, wazuh-dashboard

#1911 Bump to 4.3.10
  CHANGELOG.md
  VERSION
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-manager/debian/changelog
  macos/specs/wazuh-agent.pkgproj
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  tests/unattended/install/test_unattended.py
  tests/unattended/unit/suites/test-common.sh
  tests/unattended/unit/suites/test-dashboard.sh
  unattended_installer/install_functions/installVariables.sh
Labels: hacktoberfest, hacktoberfest-accepted

#1910 Fixing different typos in WPK generation
  wpk/run.sh
Labels: wpk, enhancement

#1914 4.3 md markdownlint
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
