Repository wazuh/wazuh-packages, pull requests merged in 2023-01, with the labels that each got.

#2010 Remove parameter `-b` to `depothelper`
  hp-ux/generate_wazuh_packages.sh
Labels: type: bug, hp-ux

#2001 Added new function checkFilebeatURL
  tests/unattended/install/test_unattended.py
  unattended_installer/builder.sh
Labels: type: feature, component: installation-assistant

#1951 Added lsof as a dependency of the unattended installer
  tests/unattended/install/test_unattended.py
  unattended_installer/install_functions/checks.sh
  unattended_installer/install_functions/installCommon.sh
Labels: type: bug, installation assistant

#1992 Add double-quoting to `config.yml` IPs to avoid errors with the parser
  documentation-templates/wazuh/config.yml
  unattended_installer/config/certificate/config.yml
Labels: type: refactor, component: cert-tool

#2026 Change the relative path used in checkFilebeat for a defined path variable
  unattended_installer/builder.sh
Labels: type: bug, component: installation-assistant, component: installation-assistant-builder

#2022 Remove parameter -b to depothelper
  hp-ux/generate_wazuh_packages.sh
Labels: type: bug, hp-ux

#2032 Avoid doing Wazuh Indexer backup if not necessary
  stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer.service
  unattended_installer/install_functions/indexer.sh
  unattended_installer/install_functions/installCommon.sh
  unattended_installer/install_functions/installMain.sh
  unattended_installer/passwords_tool/passwordsFunctions.sh
Labels: type: bug, component: installation-assistant, component: installation-assistant-builder

#2060 Fix Alpine package ossec.conf creation
  alpine/SPECS/wazuh-agent/APKBUILD
  alpine/SPECS/wazuh-agent/wazuh-agent.post-install
Labels: package, release/4.4, module/rootcheck
