Repository wazuh/wazuh-packages, pull requests merged in 2023-12, with the labels that each got.

#2720 Update release date for 4.7.2
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/copyright
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type/change

#2684 Ensure <indexer> config is present in ossec.conf after upgrade via deb package
  debs/SPECS/wazuh-manager/debian/postinst
Labels: level/task, type/bug

#2695 Add content database in RPM and DEB packages
  debs/SPECS/wazuh-manager/debian/postinst
  debs/SPECS/wazuh-manager/debian/rules
  debs/build.sh
  debs/generate_debian_package.sh
  rpms/SPECS/wazuh-manager.spec
  rpms/build.sh
  rpms/generate_rpm_package.sh
Labels: level/task, type/enhancement
