Repository wazuh/wazuh-packages, pull requests merged in 2023-02, with the labels that each got.

#2068 Bump master to 4.6.0
  CHANGELOG.md
  VERSION
  aix/SPECS/wazuh-agent-aix.spec
  alpine/SPECS/wazuh-agent/APKBUILD
  alpine/SPECS/wazuh-agent/wazuh-agent.post-install
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-manager/debian/changelog
  macos/specs/wazuh-agent.pkgproj
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  tests/unattended/unit/suites/test-common.sh
  tests/unattended/unit/suites/test-dashboard.sh
  unattended_installer/install_functions/installVariables.sh
Labels: bump

#1861 Improve command to change user and group from version 4.2.x to 4.x.x
  debs/SPECS/wazuh-manager/debian/postinst
  rpms/SPECS/wazuh-manager.spec
Labels: upgrade

#2053 Fix init.d file installation for Alma Linux and Rocky Linux
  .github/actions/ghcr-pull-and-push/build_and_push_image_to_ghcr.sh
  .github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh
  .github/actions/test-install-enable/install_and_enable.sh
  .github/workflows/build-deb-packages.yml
  .github/workflows/build-rpm-packages.yml
  .github/workflows/clean-worflow-runs.yml
  .github/workflows/test-install-and-enable-deb.yml
  .github/workflows/test-install-and-enable-rpm.yml
  .github/workflows/upload-deb-images.yml
  .github/workflows/upload-rpm-images.yml
  debs/Debian/amd64/Dockerfile
  debs/Debian/i386/Dockerfile
  debs/generate_debian_package.sh
  macos/generate_wazuh_packages.sh
  rpms/CentOS/6/i386/CentOS-Base.repo
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  rpms/generate_rpm_package.sh
  stack/indexer/rpm/wazuh-indexer.spec
  unattended_installer/common_functions/common.sh
Labels: type: bug, component: agent/rpm, component: manager/rpm

#2085 Fix the new GitHub Actions tests
  .github/workflows/build-deb-packages.yml
  .github/workflows/build-rpm-packages.yml
  .github/workflows/upload-deb-images.yml
  .github/workflows/upload-rpm-images.yml
  debs/build.sh
  rpms/build.sh
Labels: type: bug, component: gh-actions

#2070 Avoid installing `init.d` services when `init.d` is completely deprecated
  .github/actions/test-install-components/install_component.sh
  .github/actions/test-install-enable/install_and_enable.sh
  .github/workflows/build-deb-packages.yml
  .github/workflows/test-install-deb.yml
  .github/workflows/test-install-rpm.yml
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  stack/indexer/rpm/build_package.sh
  stack/indexer/rpm/wazuh-indexer.spec
  unattended_installer/install_functions/installCommon.sh
  unattended_installer/passwords_tool/passwordsFunctions.sh
Labels: type: bug, component: all-packages

#2098 Fixed Debian expired keys in Dockerfiles
  debs/Debian/amd64/Dockerfile
  debs/Debian/arm64/Dockerfile
  debs/Debian/armhf/Dockerfile
  debs/Debian/i386/Dockerfile
  debs/Debian/ppc64le/Dockerfile
  stack/dashboard/deb/docker/amd64/Dockerfile
  stack/indexer/deb/docker/amd64/Dockerfile
  windows/Dockerfile
  wpk/common/Dockerfile
Labels: type:backport
