Repository wazuh/wazuh-packages, pull requests merged in 2024-01, with the labels that each got.

#2736 Bump version to 4.8.2
  CHANGELOG.md
  VERSION
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/copyright
  macos/specs/wazuh-agent-arm64.pkgproj
  macos/specs/wazuh-agent-intel64.pkgproj
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  solaris/solaris10/pkginfo
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
  tests/unattended/unit/suites/test-common.sh
  tests/unattended/unit/suites/test-dashboard.sh
  tests/unattended/unit/suites/test-indexer.sh
  unattended_installer/install_functions/installVariables.sh
Labels: type/maintenance

#2748 Remove flag --download-content
  debs/SPECS/wazuh-manager/debian/rules
  debs/build.sh
  debs/generate_debian_package.sh
  rpms/SPECS/wazuh-manager.spec
  rpms/build.sh
  rpms/generate_rpm_package.sh
Labels: level/task, type/enhancement

#2746 Merge 4.8.0 into 4.8.1
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-manager/debian/changelog
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  stack/dashboard/deb/debian/changelog
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/base/builder.sh
  stack/indexer/base/generate_base.sh
  stack/indexer/deb/build_package.sh
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/rules
  stack/indexer/indexer-ism-init.sh
  stack/indexer/rpm/build_package.sh
  stack/indexer/rpm/wazuh-indexer.spec
  unattended_installer/builder.sh
Labels: type/maintenance

#2751 Merge 4.8.2 into master
  CHANGELOG.md
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-manager/debian/changelog
  ova/generate_ova.sh
  ova/wazuh_ovf_template
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  stack/dashboard/deb/debian/changelog
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/base/builder.sh
  stack/indexer/base/files/usr/lib/systemd/system/wazuh-indexer-performance-analyzer.service
  stack/indexer/base/generate_base.sh
  stack/indexer/deb/build_package.sh
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/rules
  stack/indexer/indexer-ism-init.sh
  stack/indexer/rpm/build_package.sh
  stack/indexer/rpm/wazuh-indexer.spec
  unattended_installer/builder.sh
  unattended_installer/passwords_tool/passwordsFunctions.sh
Labels: type/maintenance

#2755 Update release date for 4.8.0
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/copyright
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  solaris/solaris10/pkginfo
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type/maintenance

#2738 Add xz utils as requirement
  debs/SPECS/wazuh-manager/debian/control
  rpms/SPECS/wazuh-manager.spec
Labels: level/subtask, type/bug

#2764 Merge 4.8.1 into 4.8.2
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/control
  debs/SPECS/wazuh-manager/debian/copyright
  debs/SPECS/wazuh-manager/debian/postinst
  debs/SPECS/wazuh-manager/debian/rules
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  solaris/solaris10/pkginfo
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type/maintenance

#2768 Merge 4.8.2 into master
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/control
  debs/SPECS/wazuh-manager/debian/copyright
  debs/SPECS/wazuh-manager/debian/postinst
  debs/SPECS/wazuh-manager/debian/rules
  ova/assets/steps.sh
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type/maintenance
