Repository wazuh/wazuh-packages, pull requests merged in 2024-02, with the labels that each got.

#2804 keystore tool RPM and DEB packages creation
  rpms/SPECS/wazuh-manager.spec
Labels: level/task, type/enhancement

#2824 Bump version to 5.0.0
  CHANGELOG.md
  VERSION
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/copyright
  macos/specs/wazuh-agent-arm64.pkgproj
  macos/specs/wazuh-agent-intel64.pkgproj
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  solaris/solaris10/pkginfo
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
  tests/unattended/unit/suites/test-common.sh
  tests/unattended/unit/suites/test-dashboard.sh
  tests/unattended/unit/suites/test-indexer.sh
  unattended_installer/builder.sh
  unattended_installer/install_functions/installVariables.sh
Labels: type/maintenance

#2843 Update release date for 4.7.3
  aix/SPECS/wazuh-agent-aix.spec
  debs/SPECS/wazuh-agent/debian/changelog
  debs/SPECS/wazuh-agent/debian/copyright
  debs/SPECS/wazuh-manager/debian/changelog
  debs/SPECS/wazuh-manager/debian/copyright
  rpms/SPECS/wazuh-agent.spec
  rpms/SPECS/wazuh-manager.spec
  solaris/solaris10/pkginfo
  stack/dashboard/deb/debian/changelog
  stack/dashboard/deb/debian/copyright
  stack/dashboard/rpm/wazuh-dashboard.spec
  stack/indexer/deb/debian/changelog
  stack/indexer/deb/debian/copyright
  stack/indexer/rpm/wazuh-indexer.spec
Labels: type/change
